# version: "3.8"
services:
  app:
    build: .
    container_name: monolito-node
    #volumes:
    #  - .:/usr/src/app
    #  - ./db-loja.sqlite:/usr/src/app/db-loja.sqlite
    ports:
      - "3001:3000"
    working_dir: /usr/src/app
    command: npm run dev
    # command: sh
    tty: true
    volumes:
      - .:/usr/src/app:delegated
      - ./db-loja.sqlite:/usr/src/app/db-loja.sqlite
    # user: "1000:1000"